#pragma config(UART_Usage, UART1, uartUserControl, baudRate38400, IOPins, None, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "BNSlib_HC05.h"

task main()
{
	writeDebugStreamLine("Team BNS HC05 AT Commands Demo!");
	writeDebugStreamLine("Note: Ensure the 'Key' pin is connected to a 3.3V source (or 5V) and powercycle the HC05!");
	writeDebugStreamLine("    : You will know you're in AT mode when the light blinks at ~2sec intervals.\n");

	// Whenever you are in AT mode on an HC05, the default baudrate is 38400!
	setBaudRate(UART1, baudRate38400);

	// Execute several AT commands if we detect an HC05 module connected.
	if (bnsATTestConnection(UART1))
	{
		bnsATGetVersion(UART1);
		bnsATGetName(UART1);
		bnsATSetBaudrate(UART1, 57600, 1, 0);
		bnsATGetBaudrate(UART1);

		bnsATSetName(UART1, "TEAM BNS");
	}

  writeDebugStreamLine("Done!");
  while(1==1){;}
}
