#pragma config(UART_Usage, UART1, uartUserControl, baudRate38400, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  IME1,           sensorQuadEncoderOnI2CPort,    , AutoAssign)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// ------------------------------------------------------------------------
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// The author can be contacted by email at jmarple@umass.edu
//
// ------------------------------------------------------------------------
#include "BNSlib_HC05.h"

// This task continuously transmits sensor data.
task transmitSensorData
{
	int previousIME1Value = SensorValue[IME1];
	delay(50);

	while(1==1)
	{
		// Calculate the velocity from the IME's and create string to send with all that data
		string sendingStr;
		stringFormat(sendingStr, "E%d,%d\n", -(SensorValue[IME1]-previousIME1Value), motor[port1]);

		// Send Data
		bnsSerialSend(UART1, (char*)&sendingStr);

		previousIME1Value = SensorValue[IME1];
		delay(50);
	}
}

task main()
{
	// This should match what the AT command set the baudrate to!
	setBaudRate(UART1, baudRate57600);

	startTask(transmitSensorData);

	while(1==1)
	{
		// Accelerate the motors
		for (int i = 0; i < 127; i++)
		{
			motor[port1] = i;
			delay(50);
	  }

	  // Decelerate the motors
		for (int i = 127; i > 0; i--)
		{
			motor[port1] = i;
			delay(50);
		}
	}
}
